sudo: required

language:
   - scala

scala:
   - "2.11.11"

jdk:
   - openjdk8

services:
   - docker

env:
   global:
      - TAG=${TRAVIS_TAG:-${TRAVIS_COMMIT:0:7}}

branches:
   only:
      - master

addons:
   apt:
      packages:
         - make
         - python3
         - python3-pip

cache:
   directories:
      - "$HOME/.cache/pip"
      - "$HOME/.gradle"
      - "$HOME/.ivy2"
      - "$HOME/.m2"
      - "$HOME/.sbt"
      - ./archives
      - ./sratch/dot-local
      - ./scratch/pip-cache

before_install:
   - mkdir -p $HOME/.ivy2 $HOME/.m2 $HOME/.sbt $HOME/.gradle $HOME/.cache/pip

install:
   - pip3 install wheel
   - docker pull jamesmcclain/jupyter-geopyspark:stage0

script:
   - .travis/touch-blobs.sh
   - TRAVIS=1 TAG=$TAG make -d archives/netcdfAll-5.0.0-SNAPSHOT.jar
   - TRAVIS=1 TAG=$TAG make -d archives/gdal-and-friends.tar.gz
   - TRAVIS=1 TAG=$TAG make stage2
