sudo: required

language:
   - scala

scala:
   - "2.11.11"

jdk:
   - openjdk8

services:
   - docker

branches:
   only:
      - master

addons:
   apt:
      packages:
         - make
         - python3
         - python3-pip

cache:
   directories:
      - "$HOME/.cache/pip"
      - "$HOME/.gradle"
      - "$HOME/.ivy2"
      - "$HOME/.m2"
      - "$HOME/.sbt"
      - ./archives
      - ./scratch/

before_install:
   - mkdir -p $HOME/.ivy2 $HOME/.m2 $HOME/.sbt $HOME/.gradle $HOME/.cache/pip
   - docker pull jamesmcclain/jupyter-geopyspark:stage0
   - docker pull openjdk:8-jdk

install:
   - pip3 install wheel

script:
   - TRAVIS=1 make archives/netcdfAll-5.0.0-SNAPSHOT.jar
   - TRAVIS=1 make archives/gdal-and-friends.tar.gz
   - TRAVIS=1 make archives/geopyspark-and-friends.tar.gz
   - TRAVIS=1 make stage2
