sudo: required

language:
   - scala

scala:
   - "2.11.11"

jdk:
   - openjdk8

services:
   - docker

env:
   global:
      - CLEAN_TRAVIS_TAG=${TRAVIS_TAG/[[:space:]]/}
      - TAG=${CLEAN_TRAVIS_TAG:-${TRAVIS_COMMIT:0:7}}

branches:
   only:
      - master

addons:
   apt:
      packages:
         - make

script:
   - TRAVIS=1 TAG=$TAG make image

after_success:
   - if [ "$QUAY_USERNAME" != "" -a "$QUAY_PASSWORD" != "" ]; then
     docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io;
     TRAVIS=1 TAG=$TAG make publish;
     fi
